import type { IntegrationConfig, IntegrationProvider, SendTaskInput, SendTaskResult } from '../types';

interface CodexConfig extends IntegrationConfig {
  claudeApiKey?: string;
  targetRepoUrl?: string;
  targetRepoBranch?: string;
  autoMerge?: boolean;
}

export class CodexProvider implements IntegrationProvider {
  provider = 'codex';

  isConfigured(config: IntegrationConfig): boolean {
    const c = config as CodexConfig;
    return !!(c.claudeApiKey && c.targetRepoUrl);
  }

  async sendTask(task: SendTaskInput, config: IntegrationConfig): Promise<SendTaskResult> {
    const c = config as CodexConfig;
    if (!c.claudeApiKey || !c.targetRepoUrl) {
      throw new Error(
        'Codex integration not configured. Set claudeApiKey and targetRepoUrl in settings.'
      );
    }

    // V2: Create GitHub PR with code generation
    // Step 1: Parse repo URL to get owner/repo
    const match = c.targetRepoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
    if (!match) throw new Error(`Invalid GitHub URL: ${c.targetRepoUrl}`);

    const [, owner, repo] = match;
    const branch = `feedback-${task.sessionId.substring(0, 8)}`;

    // Step 2: Create GitHub PR (requires GITHUB_TOKEN for the target repo)
    // For now: mock PR creation with the task details
    const prNumber = Math.floor(Math.random() * 10000) + 1000;
    const prUrl = `${c.targetRepoUrl}/pull/${prNumber}`;

    const prBody = [
      `## Feedback-Driven Improvement`,
      ``,
      `**Feedback:** ${task.title}`,
      `**Description:** ${task.description}`,
      `**Session:** ${task.sessionId}`,
      ``,
      `### Implementation Plan`,
      `This PR implements code changes based on user feedback.`,
      ``,
      `**Claude Code Generation:** In progress...`,
      `- [ ] Code changes reviewed by technical team`,
      `- [ ] Product impact assessed by non-technical stakeholders`,
      `- [ ] Ready to merge and deploy`,
      ``,
      `---`,
      `*Generated by FeedbackAgent — transforming user feedback into code improvements*`,
    ].join('\n');

    console.log(`[codex] Creating PR for: ${task.title}`);
    console.log(`[codex] Owner: ${owner}, Repo: ${repo}`);
    console.log(`[codex] Branch: ${branch}`);
    console.log(`[codex] PR: #${prNumber}`);

    // TODO: Implement full flow:
    // 1. Call Claude API via @feedbackagent/ai/codex
    // 2. Get code changes + implementation plan
    // 3. Clone repo, apply changes, commit to new branch
    // 4. Push branch to GitHub
    // 5. Create PR via GitHub API with detailed body
    // 6. Add code review checklist and implementation details

    return {
      externalId: String(prNumber),
      externalUrl: prUrl,
      provider: 'codex',
    };
  }
}

export class ClaudeCodeProvider implements IntegrationProvider {
  provider = 'claude';

  isConfigured(config: IntegrationConfig): boolean {
    const c = config as CodexConfig;
    return !!(c.claudeApiKey && c.targetRepoUrl);
  }

  async sendTask(task: SendTaskInput, config: IntegrationConfig): Promise<SendTaskResult> {
    const c = config as CodexConfig;
    if (!c.claudeApiKey || !c.targetRepoUrl) {
      throw new Error(
        'Claude integration not configured. Set claudeApiKey and targetRepoUrl in settings.'
      );
    }

    // V2: Same flow as Codex (Claude generates the code via Claude API)
    // Future: Could route to Claude Code via MCP for interactive development
    const match = c.targetRepoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
    if (!match) throw new Error(`Invalid GitHub URL: ${c.targetRepoUrl}`);

    const [, owner, repo] = match;
    const branch = `claude-improvement-${task.sessionId.substring(0, 8)}`;
    const prNumber = Math.floor(Math.random() * 10000) + 2000;
    const prUrl = `${c.targetRepoUrl}/pull/${prNumber}`;

    const prBody = [
      `## Claude AI Code Improvement`,
      ``,
      `**Feedback:** ${task.title}`,
      `**Description:** ${task.description}`,
      `**Session:** ${task.sessionId}`,
      ``,
      `### Implementation Strategy`,
      `Claude AI has analyzed the feedback and generated code changes.`,
      ``,
      `**Review Checklist:**`,
      `- [ ] Code quality and style alignment`,
      `- [ ] Performance implications`,
      `- [ ] Breaking changes assessment`,
      `- [ ] Documentation updates`,
      `- [ ] Test coverage`,
      `- [ ] Product impact from non-technical perspective`,
      ``,
      `---`,
      `*AI-Generated Code by FeedbackAgent + Claude*`,
    ].join('\n');

    console.log(`[claude] Creating PR for: ${task.title}`);
    console.log(`[claude] Owner: ${owner}, Repo: ${repo}`);
    console.log(`[claude] Branch: ${branch}`);
    console.log(`[claude] PR: #${prNumber}`);

    return {
      externalId: String(prNumber),
      externalUrl: prUrl,
      provider: 'claude',
    };
  }
}
